In [1]:
import tensorflow as tf
import numpy as np

In [3]:

dnn_model = tf.saved_model.load('../dnn_model/1')


In [4]:
list(dnn_model.variables)


[<tf.Variable 'mean:0' shape=(9,) dtype=float32, numpy=
 array([5.4777069e+00, 1.9531847e+02, 1.0486943e+02, 2.9902517e+03,
        1.5559236e+01, 7.5898087e+01, 1.7834395e-01, 1.9745223e-01,
        6.2420380e-01], dtype=float32)>,
 <tf.Variable 'variance:0' shape=(9,) dtype=float32, numpy=
 array([2.8800762e+00, 1.0850414e+04, 1.4466995e+03, 7.0989681e+05,
        7.7550263e+00, 1.3467321e+01, 1.4653738e-01, 1.5846485e-01,
        2.3457341e-01], dtype=float32)>,
 <tf.Variable 'count:0' shape=() dtype=int64, numpy=314>,
 <tf.Variable 'dense_5/kernel:0' shape=(9, 64) dtype=float32, numpy=
 array([[-1.19783975e-01, -2.20074933e-02,  3.02790739e-02,
         -1.11856677e-01,  2.06361189e-01,  2.99330622e-01,
         -2.16448441e-01,  1.31422579e-01, -2.62755692e-01,
         -1.09387161e-02,  3.01990896e-01,  1.82279777e-02,
         -1.64253324e-01, -1.27139568e-01,  1.17469609e-01,
         -1.81321427e-01, -6.42657652e-02, -2.83252656e-01,
         -1.51940092e-01, -3.42511535e-01, 

In [5]:
dnn_model.variables[0]

<tf.Variable 'mean:0' shape=(9,) dtype=float32, numpy=
array([5.4777069e+00, 1.9531847e+02, 1.0486943e+02, 2.9902517e+03,
       1.5559236e+01, 7.5898087e+01, 1.7834395e-01, 1.9745223e-01,
       6.2420380e-01], dtype=float32)>

In [6]:

print(list(dnn_model.signatures.keys()))
infer = dnn_model.signatures["serving_default"]
print(infer.structured_outputs)



['serving_default']
{'dense_7': TensorSpec(shape=(None, 1), dtype=tf.float32, name='dense_7')}


In [7]:
uno=tf.constant([8,390.0,190.0,3850.0,8.5,70,0,0,1])
uno

<tf.Tensor: id=974, shape=(9,), dtype=float32, numpy=
array([8.00e+00, 3.90e+02, 1.90e+02, 3.85e+03, 8.50e+00, 7.00e+01,
       0.00e+00, 0.00e+00, 1.00e+00], dtype=float32)>

In [8]:
infer(uno)['dense_7'].numpy()[0][0]


15.818567

In [9]:
uno=tf.constant([8,351.0,153.0,4154.0,13.5,11,0,0,1])
infer(uno)['dense_7'].numpy()[0][0]

73.63701

In [10]:
uno=tf.constant([4,121.0,112.0,2868.0,15.5,73,1,0,0])
infer(uno)['dense_7'].numpy()[0][0]

19.456448